/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuditRouteImport } from './routes/audit'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as BulkRouteImport } from './routes/bulk'
import { Route as ChangesRouteImport } from './routes/changes'
import { Route as CheckRouteImport } from './routes/check'
import { Route as CompareRouteImport } from './routes/compare'
import { Route as CoverageRouteImport } from './routes/coverage'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as InboxRouteImport } from './routes/inbox'
import { Route as MemosRouteImport } from './routes/memos'
import { Route as PipelineRouteImport } from './routes/pipeline'
import { Route as PortfolioRouteImport } from './routes/portfolio'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RulesRouteImport } from './routes/rules'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SourcesRouteImport } from './routes/sources'
import { Route as WorkspaceRouteImport } from './routes/workspace'
import { Route as ApiPublicCronRecheckRouteImport } from './routes/api/public/cron/recheck'
import { Route as ApiPublicV1LookupAddressIdRouteImport } from './routes/api/public/v1/lookup.$addressId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuditRoute = AuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const BulkRoute = BulkRouteImport.update({
  id: '/bulk',
  path: '/bulk',
  getParentRoute: () => rootRouteImport,
} as any)
const ChangesRoute = ChangesRouteImport.update({
  id: '/changes',
  path: '/changes',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckRoute = CheckRouteImport.update({
  id: '/check',
  path: '/check',
  getParentRoute: () => rootRouteImport,
} as any)
const CompareRoute = CompareRouteImport.update({
  id: '/compare',
  path: '/compare',
  getParentRoute: () => rootRouteImport,
} as any)
const CoverageRoute = CoverageRouteImport.update({
  id: '/coverage',
  path: '/coverage',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const InboxRoute = InboxRouteImport.update({
  id: '/inbox',
  path: '/inbox',
  getParentRoute: () => rootRouteImport,
} as any)
const MemosRoute = MemosRouteImport.update({
  id: '/memos',
  path: '/memos',
  getParentRoute: () => rootRouteImport,
} as any)
const PipelineRoute = PipelineRouteImport.update({
  id: '/pipeline',
  path: '/pipeline',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioRoute = PortfolioRouteImport.update({
  id: '/portfolio',
  path: '/portfolio',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RulesRoute = RulesRouteImport.update({
  id: '/rules',
  path: '/rules',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SourcesRoute = SourcesRouteImport.update({
  id: '/sources',
  path: '/sources',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkspaceRoute = WorkspaceRouteImport.update({
  id: '/workspace',
  path: '/workspace',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicCronRecheckRoute = ApiPublicCronRecheckRouteImport.update({
  id: '/api/public/cron/recheck',
  path: '/api/public/cron/recheck',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicV1LookupAddressIdRoute =
  ApiPublicV1LookupAddressIdRouteImport.update({
    id: '/api/public/v1/lookup/$addressId',
    path: '/api/public/v1/lookup/$addressId',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/audit': typeof AuditRoute
  '/auth': typeof AuthRoute
  '/bulk': typeof BulkRoute
  '/changes': typeof ChangesRoute
  '/check': typeof CheckRoute
  '/compare': typeof CompareRoute
  '/coverage': typeof CoverageRoute
  '/dashboard': typeof DashboardRoute
  '/inbox': typeof InboxRoute
  '/memos': typeof MemosRoute
  '/pipeline': typeof PipelineRoute
  '/portfolio': typeof PortfolioRoute
  '/reset-password': typeof ResetPasswordRoute
  '/rules': typeof RulesRoute
  '/settings': typeof SettingsRoute
  '/sources': typeof SourcesRoute
  '/workspace': typeof WorkspaceRoute
  '/api/public/cron/recheck': typeof ApiPublicCronRecheckRoute
  '/api/public/v1/lookup/$addressId': typeof ApiPublicV1LookupAddressIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/audit': typeof AuditRoute
  '/auth': typeof AuthRoute
  '/bulk': typeof BulkRoute
  '/changes': typeof ChangesRoute
  '/check': typeof CheckRoute
  '/compare': typeof CompareRoute
  '/coverage': typeof CoverageRoute
  '/dashboard': typeof DashboardRoute
  '/inbox': typeof InboxRoute
  '/memos': typeof MemosRoute
  '/pipeline': typeof PipelineRoute
  '/portfolio': typeof PortfolioRoute
  '/reset-password': typeof ResetPasswordRoute
  '/rules': typeof RulesRoute
  '/settings': typeof SettingsRoute
  '/sources': typeof SourcesRoute
  '/workspace': typeof WorkspaceRoute
  '/api/public/cron/recheck': typeof ApiPublicCronRecheckRoute
  '/api/public/v1/lookup/$addressId': typeof ApiPublicV1LookupAddressIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/audit': typeof AuditRoute
  '/auth': typeof AuthRoute
  '/bulk': typeof BulkRoute
  '/changes': typeof ChangesRoute
  '/check': typeof CheckRoute
  '/compare': typeof CompareRoute
  '/coverage': typeof CoverageRoute
  '/dashboard': typeof DashboardRoute
  '/inbox': typeof InboxRoute
  '/memos': typeof MemosRoute
  '/pipeline': typeof PipelineRoute
  '/portfolio': typeof PortfolioRoute
  '/reset-password': typeof ResetPasswordRoute
  '/rules': typeof RulesRoute
  '/settings': typeof SettingsRoute
  '/sources': typeof SourcesRoute
  '/workspace': typeof WorkspaceRoute
  '/api/public/cron/recheck': typeof ApiPublicCronRecheckRoute
  '/api/public/v1/lookup/$addressId': typeof ApiPublicV1LookupAddressIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/audit'
    | '/auth'
    | '/bulk'
    | '/changes'
    | '/check'
    | '/compare'
    | '/coverage'
    | '/dashboard'
    | '/inbox'
    | '/memos'
    | '/pipeline'
    | '/portfolio'
    | '/reset-password'
    | '/rules'
    | '/settings'
    | '/sources'
    | '/workspace'
    | '/api/public/cron/recheck'
    | '/api/public/v1/lookup/$addressId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/audit'
    | '/auth'
    | '/bulk'
    | '/changes'
    | '/check'
    | '/compare'
    | '/coverage'
    | '/dashboard'
    | '/inbox'
    | '/memos'
    | '/pipeline'
    | '/portfolio'
    | '/reset-password'
    | '/rules'
    | '/settings'
    | '/sources'
    | '/workspace'
    | '/api/public/cron/recheck'
    | '/api/public/v1/lookup/$addressId'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/audit'
    | '/auth'
    | '/bulk'
    | '/changes'
    | '/check'
    | '/compare'
    | '/coverage'
    | '/dashboard'
    | '/inbox'
    | '/memos'
    | '/pipeline'
    | '/portfolio'
    | '/reset-password'
    | '/rules'
    | '/settings'
    | '/sources'
    | '/workspace'
    | '/api/public/cron/recheck'
    | '/api/public/v1/lookup/$addressId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AuditRoute: typeof AuditRoute
  AuthRoute: typeof AuthRoute
  BulkRoute: typeof BulkRoute
  ChangesRoute: typeof ChangesRoute
  CheckRoute: typeof CheckRoute
  CompareRoute: typeof CompareRoute
  CoverageRoute: typeof CoverageRoute
  DashboardRoute: typeof DashboardRoute
  InboxRoute: typeof InboxRoute
  MemosRoute: typeof MemosRoute
  PipelineRoute: typeof PipelineRoute
  PortfolioRoute: typeof PortfolioRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  RulesRoute: typeof RulesRoute
  SettingsRoute: typeof SettingsRoute
  SourcesRoute: typeof SourcesRoute
  WorkspaceRoute: typeof WorkspaceRoute
  ApiPublicCronRecheckRoute: typeof ApiPublicCronRecheckRoute
  ApiPublicV1LookupAddressIdRoute: typeof ApiPublicV1LookupAddressIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audit': {
      id: '/audit'
      path: '/audit'
      fullPath: '/audit'
      preLoaderRoute: typeof AuditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bulk': {
      id: '/bulk'
      path: '/bulk'
      fullPath: '/bulk'
      preLoaderRoute: typeof BulkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/changes': {
      id: '/changes'
      path: '/changes'
      fullPath: '/changes'
      preLoaderRoute: typeof ChangesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/check': {
      id: '/check'
      path: '/check'
      fullPath: '/check'
      preLoaderRoute: typeof CheckRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compare': {
      id: '/compare'
      path: '/compare'
      fullPath: '/compare'
      preLoaderRoute: typeof CompareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coverage': {
      id: '/coverage'
      path: '/coverage'
      fullPath: '/coverage'
      preLoaderRoute: typeof CoverageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inbox': {
      id: '/inbox'
      path: '/inbox'
      fullPath: '/inbox'
      preLoaderRoute: typeof InboxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/memos': {
      id: '/memos'
      path: '/memos'
      fullPath: '/memos'
      preLoaderRoute: typeof MemosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pipeline': {
      id: '/pipeline'
      path: '/pipeline'
      fullPath: '/pipeline'
      preLoaderRoute: typeof PipelineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio': {
      id: '/portfolio'
      path: '/portfolio'
      fullPath: '/portfolio'
      preLoaderRoute: typeof PortfolioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rules': {
      id: '/rules'
      path: '/rules'
      fullPath: '/rules'
      preLoaderRoute: typeof RulesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sources': {
      id: '/sources'
      path: '/sources'
      fullPath: '/sources'
      preLoaderRoute: typeof SourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workspace': {
      id: '/workspace'
      path: '/workspace'
      fullPath: '/workspace'
      preLoaderRoute: typeof WorkspaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/cron/recheck': {
      id: '/api/public/cron/recheck'
      path: '/api/public/cron/recheck'
      fullPath: '/api/public/cron/recheck'
      preLoaderRoute: typeof ApiPublicCronRecheckRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/v1/lookup/$addressId': {
      id: '/api/public/v1/lookup/$addressId'
      path: '/api/public/v1/lookup/$addressId'
      fullPath: '/api/public/v1/lookup/$addressId'
      preLoaderRoute: typeof ApiPublicV1LookupAddressIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AuditRoute: AuditRoute,
  AuthRoute: AuthRoute,
  BulkRoute: BulkRoute,
  ChangesRoute: ChangesRoute,
  CheckRoute: CheckRoute,
  CompareRoute: CompareRoute,
  CoverageRoute: CoverageRoute,
  DashboardRoute: DashboardRoute,
  InboxRoute: InboxRoute,
  MemosRoute: MemosRoute,
  PipelineRoute: PipelineRoute,
  PortfolioRoute: PortfolioRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  RulesRoute: RulesRoute,
  SettingsRoute: SettingsRoute,
  SourcesRoute: SourcesRoute,
  WorkspaceRoute: WorkspaceRoute,
  ApiPublicCronRecheckRoute: ApiPublicCronRecheckRoute,
  ApiPublicV1LookupAddressIdRoute: ApiPublicV1LookupAddressIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
